export const ROUTER = {
    USER: {
        HOME: '/',
        ABOUT: '/about',
        CATEGORY: '/category',
        INTRODUCE: '/introduce',
        BLOG: '/blog',
        BLOGDETAIL: '/blog/:id',
        POLICY: '/policy',
        PROFILE: '/profile',
        DETAIL: '/detail/:id',
        CHECKOUT: '/checkout',
        CART : '/cart',
        TRACKING: 'tracking',
        INFO: 'info',
        SETTINGS: 'settings',
        NOTÌICATION: 'notification',
        PAYMENTSUCCESS: '/payment-successed',
        PAYMENTFAILED: '/payment-failed',
        ORDERSTATUS: '/order-status',
    },
}